projects:
  estoreql:
    schemaPath: src/graphql/schema.json
    includes:
      - ./src/frontapp/src/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
extensions:
  amplify:
    version: 3
