version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "DataSyncFunctionStack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-v41sjvexutl1"
s3_prefix = "DataSyncFunctionStack"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
